FUERZA = "FUERZA"
AGILIDAD = "AGILIDAD"
PERICIA = "PERICIA"
RESISTENCIA = "RESISTENCIA"
VIDA = "VIDA"
ATAQUE = "ATAQUE"
DEFENSA = "DEFENSA"

GUERRERO = "GUERRERO"
ARQUERO = "ARQUERO"
DEFENSOR = "DEFENSOR"
INFILTRADO = "INFILTRADO"
PJ_CLASSES = [GUERRERO, ARQUERO, DEFENSOR, INFILTRADO]

ID = "ID"
BOTA = "BOTA"
ARMA = "ARMA"
CASCO = "CASCO"
GUANTE = "GUANTE"
PECHERA = "PECHERA"
BOTAS_PATH = "resources/allitems/botas.tsv"
ARMAS_PATH = "resources/allitems/armas.tsv"
CASCOS_PATH = "resources/allitems/cascos.tsv"
GUANTES_PATH = "resources/allitems/guantes.tsv"
PECHERAS_PATH = "resources/allitems/pecheras.tsv"
ITEMS_LIST = [BOTA, ARMA, CASO, GUANTE, PECHERA]
ITEMS_SIZE = 1000000

MIN_HEIGHT = 1.3
MAX_HEIGHT = 2.0

