FUERZA = "FUERZA"
AGILIDAD = "AGILIDAD"
PERICIA = "PERICIA"
RESISTENCIA = "RESISTENCIA"
VIDA = "VIDA"
ABILITIES_LIST = [FUERZA, AGILIDAD, PERICIA, RESISTENCIA, VIDA]

ATAQUE = "ATAQUE"
DEFENSA = "DEFENSA"

GUERRERO = "GUERRERO"
ARQUERO = "ARQUERO"
DEFENSOR = "DEFENSOR"
INFILTRADO = "INFILTRADO"
PJ_CLASSES = [GUERRERO, ARQUERO, DEFENSOR, INFILTRADO]

ID = "ID"
BOTA = "BOTA"
ARMA = "ARMA"
CASCO = "CASCO"
GUANTE = "GUANTE"
PECHERA = "PECHERA"
BOTAS_PATH = "resources/allitems/botas.tsv"
ARMAS_PATH = "resources/allitems/armas.tsv"
CASCOS_PATH = "resources/allitems/cascos.tsv"
GUANTES_PATH = "resources/allitems/guantes.tsv"
PECHERAS_PATH = "resources/allitems/pecheras.tsv"
ITEMS_LIST = [BOTA, ARMA, CASCO, GUANTE, PECHERA]
ITEMS_SIZE = 1000000

GEN_CLASS = "CLASS"
GEN_HEIGHT = "HEIGHT"
GEN_BOTA = "BOTA"
GEN_ARMA = "ARMA"
GEN_CASCO = "CASCO"
GEN_GUANTE = "GUANTE"
GEN_PECHERA = "PECHERA"
GENES_LIST = [GEN_CLASS, GEN_HEIGHT, GEN_BOTA, GEN_ARMA, GEN_CASCO, GEN_GUANTE, GEN_PECHERA]

MIN_HEIGHT = 1.3
MAX_HEIGHT = 2.0

