FUERZA = "FUERZA"
AGILIDAD = "AGILIDAD"
PERICIA = "PERICIA"
RESISTENCIA = "RESISTENCIA"
VIDA = "VIDA"
ABILITIES_LIST = [FUERZA, AGILIDAD, PERICIA, RESISTENCIA, VIDA]

ATAQUE = "ATAQUE"
DEFENSA = "DEFENSA"

GUERRERO = "GUERRERO"
ARQUERO = "ARQUERO"
DEFENSOR = "DEFENSOR"
INFILTRADO = "INFILTRADO"
PJ_CLASSES = [GUERRERO, ARQUERO, DEFENSOR, INFILTRADO]

ID = "ID"
BOTA = "BOTA"
ARMA = "ARMA"
CASCO = "CASCO"
GUANTE = "GUANTE"
PECHERA = "PECHERA"
BOTAS_PATH = "resources/test/botas.tsv"
ARMAS_PATH = "resources/test/armas.tsv"
CASCOS_PATH = "resources/test/cascos.tsv"
GUANTES_PATH = "resources/test/guantes.tsv"
PECHERAS_PATH = "resources/test/pecheras.tsv"
ITEMS_LIST = [BOTA, ARMA, CASCO, GUANTE, PECHERA]
ITEMS_SIZE = 10 #1000000

GEN_HEIGHT = "HEIGHT"
GEN_BOTA = BOTA
GEN_ARMA = ARMA
GEN_CASCO = CASCO
GEN_GUANTE = GUANTE
GEN_PECHERA = PECHERA
GENES_LIST = [GEN_HEIGHT, GEN_BOTA, GEN_ARMA, GEN_CASCO, GEN_GUANTE, GEN_PECHERA]
GENES_SIZE = 6

MIN_HEIGHT = 1.3
MAX_HEIGHT = 2.0

